name: Build Container Image
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"
permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]

    permissions:
      packages: write

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - name: Checkout Entire Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4

      - name: Set up QEMU
        uses: step-security/setup-qemu-action@1d653f731ddc90c553742100d15205c94b792314 # v4.1.0

      - name: Set up Docker Buildx
        uses: step-security/setup-buildx-action@a4709e2865773e1792246433e8eb922f9743a875 # v4.1.0
        with:
          platforms: linux/${{ matrix.arch }}
      - name: Login to GitHub Container Registry
        uses: step-security/docker-login-action@bd6978fd4ef9a5f78130095b298b8a721afcb0d8 # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set Branch
        run: |
          export APPS_JSON='[{"url": "https://github.com/frappe/lms","branch": "main"}]'
          echo "APPS_JSON_BASE64=$(echo $APPS_JSON | base64 -w 0)" >> $GITHUB_ENV
          echo "FRAPPE_BRANCH=version-15" >> $GITHUB_ENV

      - name: Set Image Tag
        run: |
          echo "IMAGE_TAG=stable" >> $GITHUB_ENV
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
        with:
          repository: frappe/frappe_docker
          path: builds

      - name: Build and push
        uses: step-security/docker-build-push-action@144392094f7fc3199dda455efe3b70dbea4b72a0 # v7.2.0
        with:
          push: true
          context: builds
          file: builds/images/layered/Containerfile
          tags: >
            ghcr.io/${{ github.repository }}:${{ github.ref_name }},
            ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
          build-args: |
            "FRAPPE_BRANCH=${{ env.FRAPPE_BRANCH }}"
            "APPS_JSON_BASE64=${{ env.APPS_JSON_BASE64 }}"