name: Server Tests
on:
  push:
    branches:
      - main
  pull_request: {}
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    services:
      redis-cache:
        image: redis:alpine
        ports:
          - 13000:6379
      redis-queue:
        image: redis:alpine
        ports:
          - 11000:6379
      redis-socketio:
        image: redis:alpine
        ports:
          - 12000:6379
      mariadb:
        image: anandology/mariadb-utf8mb4:10.3
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
    - name: Harden the runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
      with:
        use-policy-store: true
        api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - name: setup python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: '3.14'
    - name: setup node
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: '24'
        check-latest: true
    - name: setup cache for bench
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ~/bench-cache
        key: ${{ runner.os }}
    - name: install bench
      run: |
        pip3 install frappe-bench
        which bench
    - name: bench init
      run: |
        if [ -d ~/bench-cache/bench.tgz ]
        then
           (cd && tar xzf ~/bench-cache/bench.tgz)
        else
          bench init ~/frappe-bench --skip-redis-config-generation --skip-assets --python "$(which python)"
          mkdir -p ~/bench-cache
          (cd && tar czf ~/bench-cache/bench.tgz frappe-bench)
        fi
    - name: add lms app to bench
      working-directory: /home/runner/frappe-bench
      run: bench get-app lms $GITHUB_WORKSPACE
    - name: create bench site
      working-directory: /home/runner/frappe-bench
      run: bench new-site --mariadb-root-password root --admin-password admin frappe.local
    - name: install lms app
      working-directory: /home/runner/frappe-bench
      run: bench --site frappe.local install-app lms
    - name: setup requirements
      working-directory: /home/runner/frappe-bench
      run: bench setup requirements --dev
    - name: block endpoints
      working-directory: /home/runner/frappe-bench
      run: bench --site frappe.local set-config block_endpoints 1
    - name: allow tests
      working-directory: /home/runner/frappe-bench
      run: bench --site frappe.local set-config allow_tests true
    - name: bench build
      working-directory: /home/runner/frappe-bench
      run: bench --site frappe.local build
    - name: run tests
      working-directory: /home/runner/frappe-bench
      run: bench --site frappe.local run-tests --app lms --coverage
    - name: Upload coverage data
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        path: /home/runner/frappe-bench/sites/coverage.xml

  coverage:
    name: Coverage Wrap Up
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - name: Clone
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Download artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4

      - name: Upload coverage data
        uses: step-security/codecov-action@db5c3605ff3c9dc7f0b2791e6bea84a561bacab8 # v7.0.0
        with:
          name: Server
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true