name: Regenerate POT file (translatable strings)
on:
  schedule:
    - cron: "00 16 * * 5"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  regenerate-pot-file:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: ["develop"]
    permissions:
      contents: write

    steps:
        - name: Harden the runner
          uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
          with:
            use-policy-store: true
            api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

        - name: Checkout
          uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
          with:
            ref: ${{ matrix.branch }}

        - name: Setup mise
          uses: step-security/mise-action@2796166110dee826668caddd4bffedae5116e7cd # v4.2.0

        - name: Run script to update POT file
          run: |
            bash ${GITHUB_WORKSPACE}/.github/helper/update_pot_file.sh
          env:
            GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
            BASE_BRANCH: ${{ matrix.branch }}
