name: Create weekly release
on:
  schedule:
    - cron: '30 3 * * 3'
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: octokit/request-action@02f5e7c637a73a3b12ed81015fa7fb5f11cc5d7d # v2.x
        with:
          route: POST /repos/{owner}/{repo}/pulls
          owner: frappe
          repo: lms
          title: |-
            "chore: merge 'develop' into 'main'"
          body: "Automated weekly release"
          base: main
          head: develop
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}