name: Create weekly release
on:
  schedule:
    - cron: '30 3 * * 3'
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - uses: step-security/octokit-request-action@08f4100811cf1da063e5da53aad592beafc7d9de # v3.0.0
        with:
          route: POST /repos/{owner}/{repo}/pulls
          owner: frappe
          repo: lms
          title: |-
            "chore: merge 'develop' into 'main'"
          body: "Automated weekly release"
          base: main
          head: develop
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}