name: Semantic Pull Request

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  # This workflow contains a single job called "build"
  semantic:
    name: Validate PR title
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - uses: zeke/semantic-pull-requests@f4916f442d077624ea7bc24751be187be3c3ac9f # main
